workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set Java 17 explicitly
        script: |
          JAVA_HOME=$JAVA_HOME_17
          echo "JAVA_HOME=$JAVA_HOME_17" >> $CM_ENV
          export JAVA_HOME=$JAVA_HOME_17
          export PATH=$JAVA_HOME_17/bin:$PATH
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
